WHENEVER SQLERROR EXIT SQL.SQLCODE

CONNECT dbc/dbc_test_123@//localhost:1521/XEPDB1

CREATE TABLE properties (
  property_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(200) NOT NULL,
  property_value VARCHAR2(1000),
  enabled NUMBER(1) DEFAULT 1 NOT NULL CHECK (enabled IN (0, 1)),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT properties_name_uk UNIQUE (name)
);

CREATE TABLE documents (
  document_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR2(200) NOT NULL,
  body_clob CLOB,
  payload_blob BLOB,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE property_audit (
  audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  property_id NUMBER NOT NULL,
  old_value VARCHAR2(1000),
  new_value VARCHAR2(1000),
  changed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT property_audit_property_fk
    FOREIGN KEY (property_id) REFERENCES properties(property_id)
);

CREATE OR REPLACE TRIGGER properties_audit_trg
AFTER UPDATE OF property_value ON properties
FOR EACH ROW
WHEN (OLD.property_value != NEW.property_value OR (OLD.property_value IS NULL AND NEW.property_value IS NOT NULL) OR (OLD.property_value IS NOT NULL AND NEW.property_value IS NULL))
BEGIN
  INSERT INTO property_audit (property_id, old_value, new_value)
  VALUES (:OLD.property_id, :OLD.property_value, :NEW.property_value);
END;
/

CREATE OR REPLACE TRIGGER properties_updated_at_trg
BEFORE UPDATE ON properties
FOR EACH ROW
BEGIN
  :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

INSERT INTO properties (name, property_value, enabled)
VALUES ('com.sample.property1', 'alpha', 1);
INSERT INTO properties (name, property_value, enabled)
VALUES ('com.sample.property2', 'beta', 1);
INSERT INTO properties (name, property_value, enabled)
VALUES ('com.sample.feature.disabled', 'false', 0);
INSERT INTO properties (name, property_value, enabled)
VALUES ('org.example.timeout.seconds', '30', 1);

INSERT INTO documents (title, body_clob, payload_blob)
VALUES ('Sample document', TO_CLOB('This CLOB can be viewed and edited in dbc.'), EMPTY_BLOB());

COMMIT;
